# SPDX-FileCopyrightText: Elfi Ox <https://github.com/elfi-ox>
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["preview.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Ba Nyar Naing <https://github.com/devnyar>"
SPDX-License-Identifier = "CC0-1.0"
